"""Prompt templates for log analysis."""

from .system import (
    PRIMARY_ANALYSIS_SYSTEM_PROMPT,
    FINAL_REPORT_SYSTEM_PROMPT,
    RAG_MITRE_QUERY_PROMPT,
)
from .log_analysis import (
    PRIMARY_ANALYSIS_USER_PROMPT,
    FINAL_REPORT_USER_PROMPT,
)

__all__ = [
    "PRIMARY_ANALYSIS_SYSTEM_PROMPT",
    "FINAL_REPORT_SYSTEM_PROMPT",
    "RAG_MITRE_QUERY_PROMPT",
    "PRIMARY_ANALYSIS_USER_PROMPT",
    "FINAL_REPORT_USER_PROMPT",
]
